Repository lucianmot/acebook-off-the-rails, pull requests merged in 2019-07, with the labels that each got.

#1 task: setup test coverage
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: setup

#6 setup: setup devise for user model
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20190717133744_devise_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: setup

#7 created index page
  app/controllers/root_controller.rb
  app/views/root/index.html.erb
  config/routes.rb
  spec/features/index_spec.rb
Labels: help wanted

#17 Feature test email
  app/views/root/index.html.erb
  spec/features/user_enters_valid_email_spec.rb
  spec/features/web_helpers.rb
Labels: bug, duplicate, help wanted, invalid, wontfix

#18 Table relationships
  Gemfile
  Gemfile.lock
  app/models/post.rb
  app/models/user.rb
  app/views/posts/index.html.erb
  app/views/posts/new.html.erb
  app/views/root/index.html.erb
  config/routes.rb
  db/migrate/20190717160519_create_posts.rb
  db/schema.rb
  spec/features/user_can_visit_their_posts_page_when_logged_in_spec.rb
  spec/rails_helper.rb
  spec/support/database_cleaner.rb
Labels: bug

#22 Debugger
  app/views/root/index.html.erb
  spec/controllers/posts_controller_spec.rb
  spec/features/user_can_submit_posts_spec.rb
  spec/features/user_can_visit_their_posts_page_when_logged_in_spec.rb
  spec/features/user_is_redirected_if_not_logged_in_spec.rb
Labels: bug, wontfix

#23 Test user email v2
  app/views/devise/registrations/new.html.erb
  app/views/root/index.html.erb
  config/initializers/devise.rb
  spec/features/user_email_is_valid_on_sign_up_spec.rb
  spec/features/user_password_is_valid_on_sign_up_spec.rb
Labels: documentation, enhancement

#30 Readme update
  README.md
Labels: documentation, enhancement, wontfix

#35 fix: move sign out so that only a user who is signed in can sign out
  app/views/root/index.html.erb
  spec/features/user_can_log_out_spec.rb
Labels: bug, enhancement, help wanted

#38 Post new lines
  app/views/posts/index.html.erb
  app/views/posts/new.html.erb
  vendor/bundle/ruby/2.5.0/cache/.nokogiri-1.8.2.gem.icloud
  vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.2/ports/archives/.libxml2-2.9.7.tar.gz.icloud
  vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.2/ports/archives/.libxslt-1.1.32.tar.gz.icloud
Labels: enhancement

#42 Delete post
  app/controllers/posts_controller.rb
  app/views/posts/index.html.erb
  app/views/posts/new.html.erb
  spec/features/user_can_delete_a_post_spec.rb
Labels: bug, enhancement, wontfix

#43 Post with user email
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/posts/display_all.html.erb
  spec/features/user_can_view_all_posts_spec.rb
Labels: bug, enhancement

#47 Update time limit
  app/views/posts/edit.html.erb
  config/application.rb
  spec/features/user_can_only_update_their_post_within_10min_of_creation_spec.rb
Labels: bug, enhancement
